### ISSUE TITLE
OnePlus 10 pro cannot finish the RRC connection

### ISSUE THREAD

**Issue by helloTkk** [srsran/srsRAN_4G#1021] opened 2022-10-27 03:36 UTC
## Issue Description ##
Dear srsRAN community, 

Hello! 

I followed this [note](https://docs.srsran.com/en/latest/app_notes/source/5g_sa_COTS/source/index.html), The srsenb and Open5GS works properly, and I have 2 COTS UE can successfully connect to it.

But for my OnePlus 10 pro, it can see the 5G SA cell and send several RACH messages, but cannot finish the RRC procedure as shown in the pcap, although I have decrease both of nr_pdsch_mcs and nr_pusch_mcs to 3 at enb.conf.

## Setup Details ##
Below is my setup:
Core network: Open5GS running on Ubuntu 20.04
gNB: srsenb
CPU: i7-12700k
USRP: Ettus Research USRP B210 with 2 VERT 900 antennas and a GPSDO
driver: UHD 3.15
COTS UE: OnePlus 10 Pro 5G

## Expected Behavior ##
OnePlus 10 pro connect to 5G SA network successfully.

## Actual Behaviour ##
UE can see the 5G cell but can’t connect to 5G SA network successfully, even cannot finish the RRC procedure. UE is not sending RRC complete messages.
[enb.txt](https://github.com/srsran/srsRAN/files/9875565/enb.txt)
[enb.log](https://github.com/srsran/srsRAN/files/9875566/enb.log)
![pcap](https://user-images.githubusercontent.com/43031500/198185303-4c7c4f12-84a0-467e-acf6-d1c8425f9b7b.jpg)

## Additional Information ##
enodeB log and enodeB configuration file are attached. I’m really unsure of how to proceed from here, any help I’ll appreciate!

**Comment by andrepuschmann** [comment] 2022-11-07 09:57
Please send full logs in info and the PCAP please.

**Comment by andrepuschmann** [comment] 2022-11-07 10:12
It's likely the same issue as in https://github.com/srsran/srsRAN/issues/1010

**Comment by helloTkk** [comment] 2022-11-08 02:39
Hi @andrepuschmann,
Thanks for your reply. Here is the logs in info and PCAP. I appreciate your help!
[enb.log](https://github.com/srsran/srsRAN/files/9957159/enb.log)
[enb_mac_nr.zip](https://github.com/srsran/srsRAN/files/9957162/enb_mac_nr.zip)

**Comment by andrepuschmann** [comment] 2022-11-08 10:05
Looking at the logs again its clear that the UL signal quality is the issue. The SNR is very weak. You need to improve this by adjusting the gains for rx/tx on both sides, also make sure that you're not getting interference from other cells on that band. Check the logs of the eNB and observe the `snr=xx` value.

**Comment by mode51software** [comment] 2023-01-30 10:37
I have the same  issue using the OnePlus 10T with Android 12 and 13. 

I also have the issue when using the OnePlus Nord 8 on Android 12. With Android 11 the OnePlus Nord 8 works fine. The chipset is clearly physically the same but the problem with the RRC Setup happens when upgraded to Android 12. So I think the upgrade must also modify the baseband behaviour in some way and the 10 Pro, 10T and Nord 8 all exhibit the same problem with srsRAN.

I note the 10T and Nord 8 (Android 12) work ok with OAI on n78.

**Comment by alexjiao2021** [comment] 2023-02-11 03:32
Same here. Suspect some parameters in RRC setup message that UE doesn't like, any chance developers can take a look?

**Comment by helloTkk** [comment] 2023-02-11 04:19
Hi. May I know what SDR/usrp model you are currently using?
________________________________
发件人: alexjiao2021 ***@***.***>
发送时间: 2023年2月10日 22:32
收件人: srsran/srsRAN ***@***.***>
抄送: Tu, Kai ***@***.***>; Author ***@***.***>
主题: Re: [srsran/srsRAN] OnePlus 10 pro cannot finish the RRC connection (Issue #1021)


Same here. Suspect some parameters in RRC setup message that UE doesn't like, any chance developers can take a look?

―

**Comment by alexjiao2021** [comment] 2023-02-11 05:24
It's LimeSDR.

**Comment by mode51software** [comment] 2023-02-11 10:25
I use the B205mini-i with an external GPSDO

**Comment by tonyprotocols** [comment] 2023-02-16 19:38
Hi, guys  I am dealing with the exact same problem. I think the problem is happening because gNB never allocate uplink resource block and never sends PUCCH dci=0_1 format message. I am not sure why becouse in the log file I can't see any error, if someone already fix this please share. Thank you!

**Comment by alexjiao2021** [comment] 2023-02-17 14:22
Should be because of ue-specific DCI format 0-0 and 1-0 in RRC setup message, should be 0-1 and 1-1.
Could you please take a look? @andrepuschmann 
![rrc_setup](https://user-images.githubusercontent.com/84055495/219680541-abb02077-265b-4cca-8f59-149d4f4db939.png)

**Comment by andrepuschmann** [comment] 2023-02-17 22:22
Hey folks,
sorry for the delay answering here. As you might know we are working on a completely new gNB for quite some time now. We will release a first version of it next week so I would ask you guys to try this again with the new release.
Thanks

**Comment by alexjiao2021** [comment] 2023-02-18 01:45
> Hey folks, sorry for the delay answering here. As you might know we are working on a completely new gNB for quite some time now. We will release a first version of it next week so I would ask you guys to try this again with the new release. Thanks

Hi Andre, will the new gNB support LimeSDR?

**Comment by mode51software** [comment] 2023-03-22 18:32
Hi I've tried with the new srsRAN O-RAN edition and the OnePlus 10T progresses through the RRC procedure now. 

I've tried TDD n78 and FDD n1, n3 and n7.

I get a registration reject but that appears to be caused by a separate issue with network slicing conf.

**Comment by andrepuschmann** [comment] 2023-03-22 19:45
Hey all, @helloTkk . can you please also use the new repo instead of this one. We won't be backporting any fixes to the SA gNB in this repo. I am closing this issue here - please create an issue in the new repo should you still see issues.

**Closed by andrepuschmann** 2023-03-22 19:45 UTC

**Comment by mode51software** [comment] 2023-03-22 19:51
Hi @helloTkk it is a B205mini with an external GPSDO enabled in the conf with clock: external. 

I used 20MHz bandwidth and 15khz scs for n1, n3 and n7, derived from the n78 example conf.
